<div class="page-head dashboard-head"><div><div class="section-kicker"><?= Auth::isAdmin()?'Business overview':'My shift' ?></div><h1>Good <?= date('H')<12?'morning':(date('H')<18?'afternoon':'evening') ?>, <?= e(explode(' ',Auth::user()['name']??'there')[0]) ?></h1><p class="lede"><?= e(date('l, d F Y')) ?> · Live operational snapshot</p></div><div class="page-actions"><a class="btn btn-outline" href="<?= e(url('sales')) ?>">View sales</a><a class="btn btn-primary" href="<?= e(url('pos')) ?>">Open POS</a></div></div>
<section class="dashboard-kpis">
 <article class="kpi dashboard-primary-kpi"><div class="kpi-label"><?= Auth::isAdmin()?'Net sales today':'My net sales today' ?></div><div class="kpi-value blue"><?= money($stats['revenue']) ?></div><div class="kpi-hint"><?php if($stats['revenue_change']!==null): ?><?= $stats['revenue_change']>=0?'↑':'↓' ?> <?= e((string)abs($stats['revenue_change'])) ?>% versus yesterday<?php else: ?>Excludes VAT and delivery · no prior-day comparison<?php endif; ?></div></article>
 <article class="kpi"><div class="kpi-label">Transactions</div><div class="kpi-value"><?= number_format($stats['transactions']) ?></div><div class="kpi-hint">Completed today</div></article>
 <article class="kpi"><div class="kpi-label"><?= Auth::isAdmin()?'Gross profit':'Expected cash' ?></div><div class="kpi-value"><?= money(Auth::isAdmin()?$stats['gross_profit']:$stats['expected_cash']) ?></div><div class="kpi-hint"><?= Auth::isAdmin()?'Net sales less recorded sale cost':'Cash sales less cash refunds' ?></div></article>
 <article class="kpi"><div class="kpi-label"><?= Auth::isAdmin()?'Cash expected':'Offline sales synced' ?></div><div class="kpi-value"><?= Auth::isAdmin()?money($stats['expected_cash']):number_format($stats['offline_synced']) ?></div><div class="kpi-hint"><?= Auth::isAdmin()?'Across today’s completed sales':'Recorded by the server today' ?></div></article>
</section>
<section class="dashboard-action-strip" aria-label="Quick actions"><a href="<?= e(url('pos')) ?>"><span>＋</span><b>New sale</b><small>Open POS terminal</small></a><?php if(Auth::isAdmin()): ?><a href="<?= e(url('grn/new')) ?>"><span>↓</span><b>Receive stock</b><small>Post a supplier delivery</small></a><a href="<?= e(url('products/new')) ?>"><span>□</span><b>Add product</b><small>Extend the catalogue</small></a><?php endif; ?><a href="<?= e(url('reports/z')) ?>"><span>✓</span><b>Close day</b><small>Reconcile the shift</small></a></section>
<?php if($stats['pending_returns']||$stats['pending_online']): ?><section class="dashboard-attention"><b>Needs attention</b><?php if($stats['pending_returns']): ?><a href="<?= e(url('returns?status=pending')) ?>"><span><?= number_format($stats['pending_returns']) ?></span> return<?= $stats['pending_returns']===1?'':'s' ?> awaiting approval →</a><?php endif; ?><?php if($stats['pending_online']): ?><a href="<?= e(url('sales?status=pending&channel=online')) ?>"><span><?= number_format($stats['pending_online']) ?></span> online payment<?= $stats['pending_online']===1?'':'s' ?> pending →</a><?php endif; ?></section><?php endif; ?>
<div class="dashboard-grid"><section class="card dashboard-recent"><div class="dashboard-section-head"><div><div class="section-kicker">Latest activity</div><h2><?= Auth::isAdmin()?'Recent orders':'My recent transactions' ?></h2></div><a href="<?= e(url('sales')) ?>">All sales →</a></div><?php if(!$recent): ?><div class="inline-empty"><b>No transactions yet</b><span>Completed sales will appear here.</span></div><?php else: ?><div class="dashboard-order-list"><?php foreach($recent as $sale): ?><?php [$sl,$sc]=status_badge($sale['status']); ?><a href="<?= e(url('sales/'.$sale['id'])) ?>"><span><b><?= e($sale['sale_number']) ?></b><small><?= e($sale['customer_name']?:'Walk-in customer') ?> · <?= e(strtoupper($sale['channel'])) ?></small></span><span><b><?= money($sale['total']) ?></b><small><?= e(date('h:i A',strtotime($sale['created_at']))) ?> · <?= e(strtoupper($sale['payment_method'])) ?></small></span><span class="badge badge-<?= $sc ?>"><?= e($sl) ?></span></a><?php endforeach; ?></div><?php endif; ?></section>
<aside class="dashboard-side"><?php if(Auth::isAdmin()): ?><section class="card"><div class="dashboard-section-head"><div><div class="section-kicker">Inventory exceptions</div><h2>Low stock</h2></div><a href="<?= e(url('products?stock=low')) ?>">Open inventory →</a></div><?php if(!$lowStock): ?><p class="muted">All active products are above their reorder point.</p><?php else: ?><div class="dashboard-exceptions"><?php foreach($lowStock as $product): ?><a href="<?= e(url('products/'.$product['id'])) ?>"><span><b><?= e($product['name']) ?></b><small><?= e($product['sku']) ?></small></span><strong><?= Product::stockOf($product) ?> / <?= (int)$product['reorder_level'] ?></strong></a><?php endforeach; ?></div><?php endif; ?></section><section class="card"><div class="section-kicker">Audit trail</div><h2>Recent system activity</h2><div class="dashboard-activity"><?php foreach($activity as $event): ?><div><span></span><p><b><?= e(ucwords(str_replace(['.','_'],' ',$event['action']))) ?></b><small><?= e($event['user_name']?:'System') ?> · <?= e(date('d M, h:i A',strtotime($event['created_at']))) ?></small></p></div><?php endforeach; ?></div></section><?php else: ?><section class="card cashier-handoff"><div class="section-kicker">Shift handoff</div><h2>Before you finish</h2><ul><li>Complete or hand off any pending customer return.</li><li>Confirm locally queued offline sales are synced.</li><li>Count the till and close your day.</li></ul><a class="btn btn-primary btn-block" href="<?= e(url('reports/z')) ?>">Start close-of-day</a></section><?php endif; ?></aside></div>
