<?php include APP_PATH . '/views/partials/inventory-tabs.php'; ?>
<div class="page-head grn-review-head"><div><div class="section-kicker">Final verification</div><h1>Review stock receipt</h1><p class="lede">Nothing has changed in inventory yet. Confirm these details to post the delivery once.</p></div><a class="btn btn-ghost" href="<?= e(url('grn/new?draft='.$reviewToken)) ?>">Back and edit</a></div>

<ol class="workflow-steps grn-steps" aria-label="Receiving progress"><li class="complete"><span>1</span><b>Delivery</b></li><li class="complete"><span>2</span><b>Items</b></li><li class="active"><span>3</span><b>Review</b></li><li><span>4</span><b>Posted</b></li></ol>

<div class="alert alert-info"><b>Posting impact:</b> <?= number_format($draft['total_quantity']) ?> unit<?= $draft['total_quantity']===1?'':'s' ?> will be added to stock and <?= money($draft['total_cost']) ?> recorded in the purchasing ledger.</div>

<div class="grn-review-layout">
    <section class="card grn-review-document">
        <div class="grn-document-head"><div><span>Supplier</span><h2><?= e($draft['supplier']) ?></h2><p><?= e($draft['supplier_reference']?:'No supplier reference') ?></p></div><span class="badge badge-blue">Awaiting confirmation</span></div>
        <div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th class="num">Qty</th><th class="num">Unit cost</th><th class="num">Line total</th></tr></thead><tbody><?php foreach($draft['lines'] as $line): ?><tr><td><span class="cell-main"><?= e($line['product_name']) ?></span><span class="cell-sub"><?= e($line['sku']) ?> · <?= $line['is_serialized']?'Serial / IMEI':'Quantity' ?></span><?php if($line['serials']): ?><details class="review-serials"><summary><?= count($line['serials']) ?> serials checked</summary><div><?php foreach($line['serials'] as $serial): ?><code><?= e($serial) ?></code><?php endforeach; ?></div></details><?php endif; ?></td><td class="num"><?= number_format($line['quantity']) ?></td><td class="num"><?= money($line['unit_cost']) ?></td><td class="num"><strong><?= money($line['quantity']*$line['unit_cost']) ?></strong></td></tr><?php endforeach; ?></tbody><tfoot><tr><td colspan="3">Purchase total</td><td class="num"><strong><?= money($draft['total_cost']) ?></strong></td></tr></tfoot></table></div>
        <?php if($draft['note']): ?><div class="grn-review-note"><span>Receiving note</span><p><?= nl2br(e($draft['note'])) ?></p></div><?php endif; ?>
    </section>
    <aside class="card grn-confirm-card"><div class="section-kicker">Commit stock</div><h2>Ready to post?</h2><p>After confirmation, this GRN becomes permanent purchasing history and stock becomes available immediately.</p><dl class="product-facts"><div><dt>Lines</dt><dd><?= count($draft['lines']) ?></dd></div><div><dt>Units</dt><dd><?= number_format($draft['total_quantity']) ?></dd></div><div><dt>Serialized units</dt><dd><?= number_format(array_sum(array_map(fn($line)=>$line['is_serialized']?$line['quantity']:0,$draft['lines']))) ?></dd></div></dl><form method="post" action="<?= e(url('grn')) ?>"><?= csrf_field() ?><input type="hidden" name="review_token" value="<?= e($reviewToken) ?>"><label class="dialog-confirm-check"><input type="checkbox" required><span>I checked the supplier, quantities, costs, and every serial number.</span></label><button class="btn btn-primary btn-block" type="submit" data-loading-label="Posting receipt…">Post GRN and update stock</button></form><a class="btn btn-ghost btn-block" href="<?= e(url('grn/new?draft='.$reviewToken)) ?>">Back and edit</a></aside>
</div>
